export interface RequestList {
    applicant:string;
    displaymachinename:string;
    epno:number;
    filepath:string;
    lastupddt:string;
    machinename:string;
    modelname:string;
    oldepno:string;
    organ:string;
    patienttype:string;
    protocoleptype:string;
    protocolname:string;
    softwareversion:string;
    status:string;
    type:string;
    uid:string;
    version:string
};